build time -- 02:45:30
running test_regrid_from_file
Traceback (most recent call last):
  File "src/ESMF/test/regrid_from_file/run_regrid_from_file.py", line 6, in <module>
    import ESMF.api.constants as constants
  File "/work/noaa/da/mpotts/sandbox/intel_2020_intelmpi_g_jedwards_pio_update/src/addon/ESMPy/src/ESMF/__init__.py", line 69, in <module>
    from ESMF.api.esmpymanager import *
  File "/work/noaa/da/mpotts/sandbox/intel_2020_intelmpi_g_jedwards_pio_update/src/addon/ESMPy/src/ESMF/api/esmpymanager.py", line 11, in <module>
    from ESMF.interface.cbindings import *
  File "/work/noaa/da/mpotts/sandbox/intel_2020_intelmpi_g_jedwards_pio_update/src/addon/ESMPy/src/ESMF/interface/cbindings.py", line 13, in <module>
    from ESMF.interface.loadESMF import _ESMF
  File "/work/noaa/da/mpotts/sandbox/intel_2020_intelmpi_g_jedwards_pio_update/src/addon/ESMPy/src/ESMF/interface/loadESMF.py", line 36, in <module>
    with open(esmfmk, 'r') as MKFILE:
FileNotFoundError: [Errno 2] No such file or directory: ''
Traceback (most recent call last):
  File "setup.py", line 273, in <module>
    'test_regrid_from_file_parallel': TestRegridFromFileParallelCommand})
  File "/apps/intel-2020.2/intel-2020.2/intelpython3/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/apps/intel-2020.2/intel-2020.2/intelpython3/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/apps/intel-2020.2/intel-2020.2/intelpython3/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 192, in run
    subprocess.check_call(cmd)
  File "/apps/intel-2020.2/intel-2020.2/intelpython3/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/apps/intel-2020.2/intel-2020.2/intelpython3/bin/python3', 'src/ESMF/test/regrid_from_file/run_regrid_from_file.py']' returned non-zero exit status 1.
